### ISSUE TITLE
[Suggestion] Fix Electrode recipes

### ISSUE THREAD

**Issue by xJon** [3TUSK/RailwayDepotWorker#1]
To go hand in hand with the https://github.com/Railcraft/Railcraft/issues/2120 fix, the current recipes still require a centre column, which should be simple to resolve now.
Could be done manually per-modpack but would be useful universally.

**Comment by 3TUSK** [comment]
Done as b512ad674c04788efc9841dd76946b9c1e7479c7

Pending CurseForge review: https://legacy.curseforge.com/minecraft/mc-mods/railway-depot-worker/files/5638841
