### ISSUE TITLE
1.4.0+build.10 crashes on launch

### ISSUE THREAD

**Issue by xJon** [3TUSK/RailwayDepotWorker#2]
https://mclo.gs/TvLhJHy
(Tested with both original and ACGaming's fork)

**Comment by 3TUSK** [comment]
This is an interesting one. 

I am pretty sure I tested in development environment before publish, but now looking at the code, I think there is one thing requiring *delicate* handling...

**Comment by 3TUSK** [comment]
Should be fixed as of 28ea073afdd4dab028dac1794ad0b77b645bea5b. Tested locally and it seems to work for me.

Just wait for new release.

https://www.curseforge.com/minecraft/mc-mods/railway-depot-worker/files/5653670

**Comment by xJon** [comment]
@3TUSK Tested and it works! But also https://github.com/3TUSK/RailwayDepotWorker/issues/3.
