### ISSUE TITLE
Fixing #1810

### ISSUE THREAD

**Issue by xJon** [3TUSK/RailwayDepotWorker#4]
Should be rather straightforward according to [this](https://github.com/Railcraft/Railcraft/issues/1810#issuecomment-2392486792) comment?

**Comment by 3TUSK** [comment]
I will take a look this weekend. 

Or next weekend. Hopefully I am not overloaded this weekend.

**Comment by 3TUSK** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/railway-depot-worker/files/5784779

I don't know if this actually fixes the issue - a sample seed and coordinates would be much appreciated.

**Comment by xJon** [comment]
Seed: `3TUSK`, coordinates: `/tp username 555 25 -450`. Can confirm it's resolved! 🎉
