### ISSUE TITLE
Optimize firestone tick handler

### ISSUE THREAD

**Issue by jchung01** [3TUSK/RailwayDepotWorker#5]
[`FirestoneTickHandler`](https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/items/firestone/FirestoneTickHandler.java) is supposed to only run on players, but the expensive operations end up being run on all entities. Non-player entities are partially handled by passing null into the inventory checker, but it can still cause a needless impact on tps due to the stream operations (see example [spark report](https://spark.lucko.me/GGUw4a76q8?hl=16961)). An early return for non-player entities should fix this. Here's the simplest possible patch:
```diff
public void tick(LivingEvent.LivingUpdateEvent event) {
        EntityLivingBase entity = event.getEntityLiving();
        ...
+       if (!(entity instanceof EntityPlayer)) return;
        EntityPlayer holder = entity instanceof EntityPlayer ? (EntityPlayer) entity : null;
        InventoryComposite.of(entity).streamStacks().forEach(stack -> FirestoneTools.trySpawnFire(entity.world, entity.getPosition(), stack, holder));
    }
```

**Comment by 3TUSK** [comment]
I will take a look this weekend. 

Or next weekend. Hopefully I am not overloaded this weekend.

------

I took a look at the spark report. The overall time cost was not that significant, though? Just 0.07% of the entire recording time. Is this truly an issue?

**Comment by jchung01** [comment]
Certainly not a priority, but it does scale on the number of entities in the world. It does seem to consistently appear as one of the higher TPS users in LivingUpdateEvent which is why I mention it. Here's a different [spark report](https://spark.lucko.me/Oy9D7IrwH9?hl=69), which shows its usage relative to other event handlers, albeit it not being the main issue.

**Comment by 3TUSK** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/railway-depot-worker/files/5790074

I made a new release. It has a revamped firestone tick handler. Instead of `instanceof` check, it subscribes to the `TickEvent.PlayerTickEvent` instead. The event is only fired for players.

> [FirestoneTickHandler](https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/items/firestone/FirestoneTickHandler.java) is supposed to only run on players

I am not 100% certain that it is supposed to only run on players, so this revamped firestone tick handler is controlled by a config option. This option is default to `true`. 

Set this option to `false` if you need the original firestone tick handler.

**Comment by jchung01** [comment]
> it subscribes to the `TickEvent.PlayerTickEvent` instead

Yeah, that seems more sensible.
Seems to be working, thanks!
