### ISSUE TITLE
Mystcraft support/integration for Worldspikes?

### ISSUE THREAD

**Issue by xJon** [3TUSK/RailwayDepotWorker#6]
It appears that currently Worldspikes don't work well in Mystcraft dimensions (https://github.com/xJon/Tekkit-SMP/issues/23). They will not load chunks in Mystrcraft dimensions after a world restart.

The player mention this being a feature in Chicken Chunks - see: https://github.com/TheCBProject/ChickenChunks/blob/1.12.x/src/main/java/codechicken/chunkloader/manager/ChunkLoaderManager.java#L609

Do you think that Mystcraft integration could be added?

**Comment by 3TUSK** [comment]
> I vaguely remember that I have seen this exact issue on a homebrewed _1.5.2_ pack. At that time, I didn't even think about it, and just manually go to the MystCraft dimension to trigger chunkloading every time I start the game.

I will see what I can do. This one isn't easy.

**Comment by xJon** [comment]
Thank you so much! Thankfully both mods have visible source.

Also, where is that quote from? I do agree that it's nice Chicken Chunks accounts for it with its Mystcraft integration, it shouldn't be taken for granted.

**Comment by 3TUSK** [comment]
That quote is mine. I quote from myself.

**Comment by xJon** [comment]
Oh wow. Good to know there are still devs from back in the day.

**Comment by 3TUSK** [comment]
https://www.curseforge.com/minecraft/mc-mods/railway-depot-worker/files/5909954

I think I found an interesting fix. From my quick test, this fix should work well.

**Comment by xJon** [comment]
Incredible, thank you so much @3TUSK, the players will be really pleased.
